### PR TITLE
feat: rewrite the format function

### LINKED ISSUE #85: [CLI] Print files that were just formatted
As of today, to know which files are formatted by `brioche fmt`, you need to run first the command with the check argument, or you could rely on some version control tools to see the diff.

Symmetrical to what is printed when the `brioche fmt --check` is run **and** there are files that are not formatted:

```bash
The following files are not formatted:
- foo
- bar
```

We could have:

```bash
The following files have been formatted:
- foo
- bar
```

Or at least a number of files that were formatted: ` 1/32 files have been formatted`.

What I wanted is just a way to inform that the formatting did actually format some files.

### PR DESCRIPTION
**Pull request by jaudiger**
Resolve #85 

Add the formatted files and better handle errors happened on a project when formatting more than once at the same time as suggested by @kylewlacy https://github.com/brioche-dev/brioche/pull/84#pullrequestreview-2174249892

### CODE REVIEW

**Comment by jaudiger** [comment]
Some examples:

```bash
cargo run -- fmt --check -p ../brioche-packages/packages/bat -p ../brioche-packages/packages/biome -p ../brioche-packages/packages/go -p ../brioche-packages/packages/biom
   Compiling brioche v0.1.1 (/Users/jaudiger/Development/git-repositories/jaudiger/brioche/crates/brioche)
    Finished `dev` profile [optimized + debuginfo] target(s) in 32.03s
     Running `target/debug/brioche fmt --check -p ../brioche-packages/packages/bat -p ../brioche-packages/packages/biome -p ../brioche-packages/packages/go -p ../brioche-packages/packages/biom`
[938µs] 0 / 0 jobs complete
The following files of project '../brioche-packages/packages/bat' are not formatted:
- /Users/jaudiger/Development/git-repositories/jaudiger/brioche-packages/packages/bat/project.bri
[106.1ms] 0 / 0 jobs complete
The following files of project '../brioche-packages/packages/biome' are not formatted:
- /Users/jaudiger/Development/git-repositories/jaudiger/brioche-packages/packages/biome/project.bri
[211.2ms] 0 / 0 jobs complete
All files of project '../brioche-packages/packages/go' are formatted

Error occurred while formatting project '../brioche-packages/packages/biom': failed to canonicalize path ../brioche-packages/packages/biom
```

```bash
cargo run -- fmt -p ../brioche-packages/packages/bat -p ../brioche-packages/packages/biome -p ../brioche-packages/packages/go -p ../brioche-packages/packages/biom        
    Finished `dev` profile [optimized + debuginfo] target(s) in 0.78s
     Running `target/debug/brioche fmt -p ../brioche-packages/packages/bat -p ../brioche-packages/packages/biome -p ../brioche-packages/packages/go -p ../brioche-packages/packages/biom`
[947µs] 0 / 0 jobs complete
The following files of project '../brioche-packages/packages/bat' have been formatted:
- /Users/jaudiger/Development/git-repositories/jaudiger/brioche-packages/packages/bat/project.bri
[106.3ms] 0 / 0 jobs complete
The following files of project '../brioche-packages/packages/biome' have been formatted:
- /Users/jaudiger/Development/git-repositories/jaudiger/brioche-packages/packages/biome/project.bri
[211.5ms] 0 / 0 jobs complete
Error occurred while formatting project '../brioche-packages/packages/biom': failed to canonicalize path ../brioche-packages/packages/biom
```

**Comment by jaudiger** [comment]
There is still one issue with that PR. Each last line from `println!()`statements seems to be eaten. I think it comes from the console reporter, but I'm unsure.

**Review by kylewlacy — APPROVED** [review]
LGTM

**Comment by kylewlacy** [comment]
> There is still one issue with that PR. Each last line from `println!()`statements seems to be eaten. I think it comes from the console reporter, but I'm unsure.

Yeah, that sounds like another issue I've seen related to the formatter where the last line of the console output gets overridden... I think the issue is that superconsole doesn't mix well with `println!`, and so doing everything through the reporter would be better

**Pull request merged**
