### PR TITLE
build: update deno_ast dependency to latest version

### PR DESCRIPTION
**Pull request by jaudiger**
Part of #81 

I preferred to split the updating of `deno_ast` and `deno_core`, since I have few issues locally that need to be resolved first before upstreaming the `deno_core` update. But didn't find any issue with the update of `deno_ast`.

I tested the modification with the following brioche commands (same as in https://github.com/brioche-dev/brioche/pull/93):

```
brioche fmt -p packages/bat
brioche check -p packages/bat
brioche build -p packages/bat
brioche build -p packages/bat -e test
brioche install -p packages/bat
```

### CODE REVIEW

**Comment by kylewlacy** [comment]
I tried running `cargo run -- run -p ../brioche-packages/examples/nodejs_frontend` and got an interesting error:

```
    Finished dev [optimized + debuginfo] target(s) in 0.79s
     Running `target/debug/brioche run -p ../brioche-packages/examples/nodejs_frontend`
ERROR run_build:evaluate: brioche_core::script::evaluate: error=error when calling default export="default" project_hash=6170fe6a918136b838ee2f0059e0251589cb51c1f9691f50cf27a2a9a0521322
Error: error when calling default

Caused by:
    Error: Could not find source file to resolve glob
        at globalThis.Brioche.glob (file:///home/kyle/Development/Brioche/brioche-packages/packages/std/core/global.bri:51:11)
        at staticSite (file:///home/kyle/Development/Brioche/brioche-packages/examples/nodejs_frontend/project.bri:7:26)
        at Module.default (file:///home/kyle/Development/Brioche/brioche-packages/examples/nodejs_frontend/project.bri:28:36)
```

I haven't dug in at all, but my guess is it's related to sourcemaps in some way. Sourcemaps get used to resolve expressions like `Brioche.glob` (and other statics) in order to determine which project to resolve it from

**Comment by kylewlacy** [comment]
Oh wait, that bug is also present on `main`... I'll look into this separately because it's unrelated to this PR

**Comment by jaudiger** [comment]
The bug has been introduced with my last PR updating deno_core dependency (https://github.com/brioche-dev/brioche/pull/93). Before this pull request, the issue is not present.

**Comment by jaudiger** [comment]
I put this PR on hold until the other issue is resolved. Do you want to revert the last PR on main?

**Comment by kylewlacy** [comment]
> I put this PR on hold until the other issue is resolved. Do you want to revert the last PR on main?

I'm gonna try to see if I can fix it first. I narrowed it down to something that changed between `deno_core` v0.214.0 and v0.215.0 [comparison](https://github.com/denoland/deno_core/compare/0.214.0...0.215.0). Looking at the diff, I have some ideas on how to fix it, but I want to see if I can write a unit test for it as well

(If it ends up taking a while to fix, then I'll roll back the PR instead)

**Comment by jaudiger** [comment]
Ok, please let me know, and thanks for looking at this! If you need anything else, don't hesitate.

**Comment by kylewlacy** [comment]
Alright, just a quick update, I pushed a branch that has a new test case plus a change that I _think_ should fix the issue: [wip/fix-stack-frames](https://github.com/brioche-dev/brioche/tree/wip/fix-stack-frames)

The new test case will fail on `main` ([`a46843d`](https://github.com/brioche-dev/brioche/commit/a46843df97881f1d8d5c302f0e0988e91685c81a)) but will pass on [`45411ff`](https://github.com/brioche-dev/brioche/tree/45411ffa4867aa0f8ec1138e235ed027ad8f42a8). I've been trying to run the test locally with the potential fix in place, but I keep getting a weird panic message:

```
fatal runtime error: failed to initiate panic, error 5
error: test failed, to rerun pass `-p brioche-core --test script_stack_frames`
```

I'll keep digging more tomorrow, but for now I think I'll revert #91 just to get `main` working again

**Comment by jaudiger** [comment]
Sure, let's do it this way !

**Comment by jaudiger** [comment]
> Alright, just a quick update, I pushed a branch that has a new test case plus a change that I _think_ should fix the issue: [wip/fix-stack-frames](https://github.com/brioche-dev/brioche/tree/wip/fix-stack-frames)
> 
> The new test case will fail on `main` ([`a46843d`](https://github.com/brioche-dev/brioche/commit/a46843df97881f1d8d5c302f0e0988e91685c81a)) but will pass on [`45411ff`](https://github.com/brioche-dev/brioche/tree/45411ffa4867aa0f8ec1138e235ed027ad8f42a8). I've been trying to run the test locally with the potential fix in place, but I keep getting a weird panic message:
> 
> ```
> fatal runtime error: failed to initiate panic, error 5
> error: test failed, to rerun pass `-p brioche-core --test script_stack_frames`
> ```

I tried your test case locally on top of this branch. And to fix the exception you have, we need to mark the function `op_brioche_stack_frames_from_exception()` as [reentrant](https://github.com/denoland/deno_core/blob/ca05c452a291ca67337ef857d8f8ea42146dbac8/ops/op2/config.rs#L24):

```rust
#[deno_core::op2(reentrant)]
#[serde]
fn op_brioche_stack_frames_from_exception(
    scope: &mut v8::HandleScope,
    exception: v8::Local<v8::Value>,
) -> Vec<StackFrame> {
    // Code
}
``` 

After this modification, the test passed, but requires updating the line number to 8 for the file name `project.bri`:

```rust
    assert_eq!(
        stack_frames,
        vec![
            TestStackFrame {
                file_name: "stack_frames.bri".to_string(),
                line_number: 3,
            },
            TestStackFrame {
                file_name: "bar.bri".to_string(),
                line_number: 4,
            },
            TestStackFrame {
                file_name: "foo.bri".to_string(),
                line_number: 4,
            },
            TestStackFrame {
                file_name: "project.bri".to_string(),
                line_number: 8,
            },
        ]
    );
```

Also running `cargo run -- run -p ../brioche-packages/examples/nodejs_frontend` worked locally 🚀

```bash
cargo run -- build -p /tmp/brioche-packages/examples/nodejs_frontend/
   Compiling brioche-core v0.1.1 (/workspace/crates/brioche-core)
   Compiling brioche v0.1.1 (/workspace/crates/brioche)
    Finished dev [optimized + debuginfo] target(s) in 1m 53s
     Running `target/debug/brioche build -p /tmp/brioche-packages/examples/nodejs_frontend/`
[3502] npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.2                                                                                                                                                                                                                                                                                              
[3502] npm notice To update run: npm install -g npm@10.8.2                                                                                                                                                                                                                                                                                                                
[3502] npm notice                                                                                                                                                                                                                                                                                                                                                         
[3530]                                                                                                                                                                                                                                                                                                                                                                    
[3530] > nodejs_frontend@0.0.0 build                                                                                                                                                                                                                                                                                                                                      
[3530] > tsc && vite build                                                                                                                                                                                                                                                                                                                                                
[3530]                                                                                                                                                                                                                                                                                                                                                                    
[3530] vite v5.2.12 building for production...                                                                                                                                                                                                                                                                                                                            
[3530] transforming...                                                                                                                                                                                                                                                                                                                                                    
[3530] ✓ 34 modules transformed.                                                                                                                                                                                                                                                                                                                                          
[3530] rendering chunks...                                                                                                                                                                                                                                                                                                                                                
[3530] computing gzip size...                                                                                                                                                                                                                                                                                                                                             
[3530] dist/index.html                   0.46 kB │ gzip:  0.30 kB                                                                                                                                                                                                                                                                                                         
[3530] dist/assets/react-CHdo91hT.svg    4.13 kB │ gzip:  2.05 kB                                                                                                                                                                                                                                                                                                         
[3530] dist/assets/index-DiwrgTda.css    1.39 kB │ gzip:  0.72 kB                                                                                                                                                                                                                                                                                                         
[3530] dist/assets/index-DVoHNO1Y.js   143.36 kB │ gzip: 46.09 kB                                                                                                                                                                                                                                                                                                         
[3530] ✓ built in 1.05s                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                          
Process 3530 [5.2s Exited 0]
Process 3502 [5.3s Exited 0]
[100%] Fetched 2240 blobs + 2939 recipes from registry
Build finished, completed 4 jobs in 17:28
Result: 34105035514d4a0f1b0ec91b294bacbd87c768ef046befabea27fc78c46be623
```

**Pull request closed without merging**
