### PR TITLE
fix: set executable bit on brioche binary if not already set

### PR DESCRIPTION
**Pull request by jaudiger**
The code changes in `self_update.rs` add logic to set the executable bit on the `brioche` binary if it's not already set. This ensures that the binary can be executed properly after a self update.

Resolve https://github.com/brioche-dev/brioche/issues/95

### CODE REVIEW

**Review by kylewlacy — COMMENTED** [review]
One tweak before this is ready to merge: setting the permissions should be done on the temp file before renaming it, not after renaming. This is so that, if the process is killed (say, with Ctrl-C), the result is either the old version of Brioche or the new version of Brioche with correct permissions

**Comment by jaudiger** [comment]
Sure, I’ll resolve when I come back !

**Comment by jaudiger** [comment]
I moved the code to apply the file permissions if necessary to the temporary file.

**Review by kylewlacy — APPROVED** [review]
Thanks for this! Finally had some time to sit down and test this out, LGTM :+1:

**Pull request merged**
